# Generated by Django 4.1.1 on 2022-09-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradclear_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='course_graduated',
            field=models.CharField(blank=True, choices=[('', '--SELECT--'), ('BSCE', 'Bachelor of Science in Civil Engineering'), ('BSEE', 'Bachelor of Science in Electrical Engineering'), ('BSME', 'Bachelor of Science in Mechanical Engineering'), ('BSIE-ICT', 'Bachelor of Science in Industrial Education major in Information and Communication Technology'), ('BSIE-HE', 'Bachelor of Science in Industrial Education major in Home Economics'), ('BTTE-CP', 'Bachelor of Technical Teachers Education major in Computer Programming'), ('BTTE-EI', 'Bachelor of Technical Teachers Education major in Electronics'), ('BTTE-AU', 'Bachelor of Technical Teachers Education major in Automotive'), ('BTTE-HVACT', 'Bachelor of Technical Teachers Education major in Heatingg, Ventilation and Air Conditioning Tecnology'), ('BTTE-E', 'Bachelor of Technical Teachers Education major in Electrical'), ('BGT-AT', 'Bachelor of Engineering Technolgy major in Architecture Technology'), ('BET-CT', 'Bachelor of Engineering Technolgy major in Civil Engineering Technology'), ('BET-ET', 'Bachelor of Engineering Technolgy major in Electrical Engineering Technology'), ('BET-EsET', 'Bachelor of Engineering Technolgy major in Electronics Engineering Technology'), ('BET-CoET', 'Bachelor of Engineering Technolgy major in Computer Engineering Technology'), ('BET-MT', 'Bachelor of Engineering Technolgy major in Mechanical & Production Engineering Technology'), ('BET-PPT', 'Bachelor of Engineering Technolgy major in Power Plant Engineering Technology'), ('BET-AT', 'Bachelor of Engineering Technolgy major in Automotive Engineering Technology')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_table',
            name='year_graduated',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Year Graduated'),
        ),
    ]
