# Generated by Django 4.0.6 on 2022-09-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradclear_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearance_form_table',
            name='course_adviser',
        ),
    ]
