# Generated by Django 4.1.1 on 2022-11-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradclear_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_form_table',
            name='student_id',
            field=models.CharField(max_length=50, verbose_name='Student Id'),
        ),
    ]
