# Generated by Django 4.0.6 on 2022-09-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradclear_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_form_table',
            name='claim',
            field=models.CharField(default='UNCLAIMED', max_length=50, null=True),
        ),
    ]
