# Generated by Django 4.0.6 on 2022-10-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradclear_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearance_form_table',
            name='academic_affairs_signature',
            field=models.CharField(default='UNAPPROVED', max_length=100, verbose_name='Academic Affairs Signature'),
        ),
        migrations.AlterField(
            model_name='clearance_form_table',
            name='accountant_signature',
            field=models.CharField(default='UNAPPROVED', max_length=100, verbose_name='Accountant Signature'),
        ),
        migrations.AlterField(
            model_name='clearance_form_table',
            name='course_adviser',
            field=models.CharField(default='NONE', max_length=100, verbose_name='Course Adviser'),
        ),
        migrations.AlterField(
            model_name='clearance_form_table',
            name='guidance_office_signature',
            field=models.CharField(default='UNAPPROVED', max_length=100, verbose_name='Guidance Signature'),
        ),
        migrations.AlterField(
            model_name='clearance_form_table',
            name='ieduc_dept_signature',
            field=models.CharField(default='UNAPPROVED', max_length=100, verbose_name='Industrial Educ. Signature'),
        ),
        migrations.AlterField(
            model_name='clearance_form_table',
            name='ieng_dept_signature',
            field=models.CharField(default='UNAPPROVED', max_length=100, verbose_name='Industrial Eng. Signature'),
        ),
        migrations.AlterField(
            model_name='clearance_form_table',
            name='it_dept_signature',
            field=models.CharField(default='UNAPPROVED', max_length=100, verbose_name='Industrial Tech. Signature'),
        ),
        migrations.AlterField(
            model_name='clearance_form_table',
            name='liberal_arts_signature',
            field=models.CharField(default='UNAPPROVED', max_length=100, verbose_name='Liberal Art Signature'),
        ),
        migrations.AlterField(
            model_name='clearance_form_table',
            name='library_signature',
            field=models.CharField(default='UNAPPROVED', max_length=100, verbose_name='Library Signature'),
        ),
        migrations.AlterField(
            model_name='clearance_form_table',
            name='mathsci_dept_signature',
            field=models.CharField(default='UNAPPROVED', max_length=100, verbose_name='Math and Science Signature'),
        ),
        migrations.AlterField(
            model_name='clearance_form_table',
            name='osa_signature',
            field=models.CharField(default='UNAPPROVED', max_length=100, verbose_name='OSA Signature'),
        ),
        migrations.AlterField(
            model_name='clearance_form_table',
            name='pe_dept_signature',
            field=models.CharField(default='UNAPPROVED', max_length=100, verbose_name='P.E. Signature'),
        ),
    ]
