# Generated by Django 4.1.1 on 2022-10-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradclear_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation '),
        ),
        migrations.AlterField(
            model_name='request_form_table',
            name='TOR',
            field=models.CharField(default='❌', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='request_form_table',
            name='clearance',
            field=models.CharField(default='❌', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='request_form_table',
            name='form_137',
            field=models.CharField(default='❌', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='request_form_table',
            name='official_receipt',
            field=models.CharField(default='❌', max_length=50, null=True),
        ),
    ]
