# Generated by Django 4.0.1 on 2022-09-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gradclear_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearance_form_table',
            name='liberal_arts_signature',
            field=models.CharField(default='UNAPPROVED', max_length=15, verbose_name='Liberal Art Signature'),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
