# Generated by Django 4.0.6 on 2022-11-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradclear_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='birthday',
            field=models.CharField(max_length=100, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='profile_picture',
            field=models.ImageField(default='Media/account.png', upload_to='uploads/'),
        ),
    ]
