# Generated by Django 4.0.6 on 2022-11-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradclear_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='student_id',
            field=models.CharField(max_length=100, null=True, verbose_name='Student ID'),
        ),
    ]
