# Generated by Django 4.0.6 on 2022-11-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradclear_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearance_form_table',
            name='course',
            field=models.CharField(default='NONE', max_length=100, null=True, verbose_name='Student Course'),
        ),
    ]
