# Generated by Django 4.0.6 on 2022-11-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradclear_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_form_table',
            name='approval_status',
            field=models.CharField(default='UNAPPROVED', max_length=15, verbose_name='Approval Status'),
        ),
    ]
