# Generated by Django 4.1.1 on 2022-11-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradclear_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearance_form_table',
            name='semester_enrolled',
            field=models.CharField(default='NONE', max_length=100, null=True, verbose_name='Semester Enrolled in TUPC'),
        ),
    ]
