# Generated by Django 4.0.6 on 2022-11-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradclear_app', '0002_alter_user_table_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='birthday',
            field=models.CharField(max_length=8, verbose_name='Birthday'),
        ),
    ]
