# Generated by Django 4.0.6 on 2022-11-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradclear_app', '0002_alter_clearance_form_table_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
    ]
