# Generated by Django 4.0.6 on 2022-11-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradclear_app', '0002_alter_clearance_form_table_academic_affairs_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearance_form_table',
            name='approval_status',
            field=models.CharField(default='0', max_length=15, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='graduation_form_table',
            name='approval_status',
            field=models.CharField(default='0', max_length=15, verbose_name='Approval Status'),
        ),
    ]
