# Generated by Django 4.0.6 on 2022-10-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradclear_app', '0002_alter_clearance_form_table_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation_form_table',
            name='addsignature1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='graduation_form_table',
            name='addsignature10',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='graduation_form_table',
            name='addsignature2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='graduation_form_table',
            name='addsignature3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='graduation_form_table',
            name='addsignature4',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='graduation_form_table',
            name='addsignature5',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='graduation_form_table',
            name='addsignature6',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='graduation_form_table',
            name='addsignature7',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='graduation_form_table',
            name='addsignature8',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='graduation_form_table',
            name='addsignature9',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='graduation_form_table',
            name='signature1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='graduation_form_table',
            name='signature10',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='graduation_form_table',
            name='signature2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='graduation_form_table',
            name='signature3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='graduation_form_table',
            name='signature4',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='graduation_form_table',
            name='signature5',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='graduation_form_table',
            name='signature6',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='graduation_form_table',
            name='signature7',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='graduation_form_table',
            name='signature8',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='graduation_form_table',
            name='signature9',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='graduation_form_table',
            name='sitsignature',
            field=models.CharField(max_length=100),
        ),
    ]
