# Generated by Django 4.0.6 on 2022-11-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradclear_app', '0002_alter_clearance_form_table_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_form_table',
            name='student_id',
            field=models.CharField(max_length=50, verbose_name='Student Id'),
        ),
    ]
