# Generated by Django 4.0.6 on 2022-11-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradclear_app', '0002_user_table_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Email Address'),
        ),
    ]
