# Generated by Django 4.1.1 on 2022-09-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradclear_app', '0002_clearance_form_table_liberal_arts_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='position',
            field=models.CharField(blank=True, default='STAFF', max_length=100, null=True, verbose_name='Position '),
        ),
    ]
