# Generated by Django 4.0.6 on 2022-11-17 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradclear_app', '0002_alter_user_table_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='id_number',
            field=models.CharField(max_length=17, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='ID Number'),
        ),
    ]
