# Generated by Django 4.0.1 on 2022-09-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradclear_app', '0002_alter_user_table_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearance_form_table',
            name='course_adviser',
            field=models.CharField(default='UNAPPROVED', max_length=15, verbose_name='Course/Shop Adviser'),
        ),
    ]
