# Generated by Django 4.0.6 on 2022-11-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradclear_app', '0003_alter_user_table_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='profile_picture',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
